name: Test & Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest ruff black mypy
      - name: Run linters
        run: |
          ruff .
          black --check .
          mypy api ingestion normalize || true
      - name: Run tests
        run: pytest -q
